name: LobbySystem
version: '${project.version}'
main: net.vybemc.lobbysystem.LobbySystem
api-version: 1.8
author: DiesesFloo
commands:
  build:
    description: Toggle building mode
  play:
    description: Play a gamemode