name: LobbySystem
version: '${project.version}'
main: net.vybemc.lobbysystem.LobbySystem
api-version: 1.8
author: DiesesFloo
commands:
  fly:
    usage: /fly [player]
    description: Toggle fly mode
  build:
    usage: /build [player]
    description: Toggle building mode